#!/bin/sh

### BEGIN INIT INFO
# Provides:             misc-modules
# Required-Start:
# Required-Stop:
# Default-Start:        S
# Default-Stop:
### END INIT INFO

modules="hello faulty"

case "$1" in
  start)
    echo "loading custom kernel modules"
    echo "loading scull"
    /bin/scull_load.sh
    for m in ${modules}; do
      echo "loading ${m}"
      /bin/module_load.sh $m
    done
    ;;
  stop)
    echo "unloading custom kernel modules"
    echo "unloading scull"
    /bin/scull_unload.sh
    for m in ${modules}; do
      echo "unloading ${m}"
      /bin/module_unload.sh $m
    done
    ;;
  *)
    echo "Usage $0 {start|stop}"
  exit 1;
esac

exit 0;
